export const sourceOptions = [
  { value: "camel", label: "camel", children: "camel" },
  { value: "camel2", label: "camel2", children: "camel2" },
  { value: "camel3", label: "camel3", children: "camel3" },
  { value: "drools", label: "drools", children: "drools" },
  { value: "drools5", label: "drools5", children: "drools5" },
  { value: "eap", label: "eap", children: "eap" },
  { value: "eap4", label: "eap4", children: "eap4" },
  { value: "eap5", label: "eap5", children: "eap5" },
  { value: "eap6", label: "eap6", children: "eap6" },
  { value: "eap7", label: "eap7", children: "eap7" },
  { value: "eap7.0", label: "eap7.0", children: "eap7.0" },
  { value: "eap7.1", label: "eap7.1", children: "eap7.1" },
  { value: "eapxp", label: "eapxp", children: "eapxp" },
  { value: "glassfish", label: "glassfish", children: "glassfish" },
  { value: "hibernate", label: "hibernate", children: "hibernate" },
  {
    value: "hibernate-search",
    label: "hibernate-search",
    children: "hibernate-search",
  },
  {
    value: "hibernate-search4",
    label: "hibernate-search4",
    children: "hibernate-search4",
  },
  { value: "hibernate3.9", label: "hibernate3.9", children: "hibernate3.9" },
  { value: "hibernate4", label: "hibernate4", children: "hibernate4" },
  { value: "hibernate5.0", label: "hibernate5.0", children: "hibernate5.0" },
  { value: "hibernate5.1", label: "hibernate5.1", children: "hibernate5.1" },
  { value: "jakarta-ee", label: "jakarta-ee", children: "jakarta-ee" },
  { value: "jakarta-ee7", label: "jakarta-ee7", children: "jakarta-ee7" },
  { value: "java", label: "java", children: "java" },
  { value: "java-ee", label: "java-ee", children: "java-ee" },
  { value: "javaee", label: "javaee", children: "javaee" },
  { value: "jbpm", label: "jbpm", children: "jbpm" },
  { value: "jbpm5", label: "jbpm5", children: "jbpm5" },
  { value: "jonas", label: "jonas", children: "jonas" },
  { value: "jrun", label: "jrun", children: "jrun" },
  { value: "log4j", label: "log4j", children: "log4j" },
  { value: "openjdk", label: "openjdk", children: "openjdk" },
  { value: "openjdk11", label: "openjdk11", children: "openjdk11" },
  { value: "openjdk18", label: "openjdk18", children: "openjdk18" },
  { value: "openjdk19", label: "openjdk19", children: "openjdk19" },
  { value: "openjdk20", label: "openjdk20", children: "openjdk20" },
  { value: "openjdk21", label: "openjdk21", children: "openjdk21" },
  { value: "openjdk8", label: "openjdk8", children: "openjdk8" },
  { value: "oraclejdk", label: "oraclejdk", children: "oraclejdk" },
  { value: "oraclejdk7", label: "oraclejdk7", children: "oraclejdk7" },
  { value: "orion", label: "orion", children: "orion" },
  { value: "resin", label: "resin", children: "resin" },
  { value: "resteasy", label: "resteasy", children: "resteasy" },
  { value: "resteasy2", label: "resteasy2", children: "resteasy2" },
  { value: "rmi", label: "rmi", children: "rmi" },
  { value: "rpc", label: "rpc", children: "rpc" },
  { value: "seam", label: "seam", children: "seam" },
  { value: "seam2", label: "seam2", children: "seam2" },
  { value: "soa", label: "soa", children: "soa" },
  { value: "soa-p", label: "soa-p", children: "soa-p" },
  { value: "soa-p5", label: "soa-p5", children: "soa-p5" },
  { value: "sonic", label: "sonic", children: "sonic" },
  { value: "sonicesb", label: "sonicesb", children: "sonicesb" },
  { value: "springboot", label: "springboot", children: "springboot" },
  { value: "thorntail", label: "thorntail", children: "thorntail" },
  { value: "weblogic", label: "weblogic", children: "weblogic" },
  { value: "websphere", label: "websphere", children: "websphere" },
];
