export const targetOptions = [
  { value: "azure-aks", label: "azure-aks", children: "azure-aks" },
  {
    value: "azure-appservice",
    label: "azure-appservice",
    children: "azure-appservice",
  },
  {
    value: "azure-container-apps",
    label: "azure-container-apps",
    children: "azure-container-apps",
  },
  {
    value: "azure-spring-apps",
    label: "azure-spring-apps",
    children: "azure-spring-apps",
  },
  { value: "camel", label: "camel", children: "camel" },
  { value: "camel2", label: "camel2", children: "camel2" },
  { value: "camel3", label: "camel3", children: "camel3" },
  { value: "camel3.1", label: "camel3.1", children: "camel3.1" },
  { value: "camel3.10", label: "camel3.10", children: "camel3.10" },
  { value: "camel3.11", label: "camel3.11", children: "camel3.11" },
  { value: "camel3.12", label: "camel3.12", children: "camel3.12" },
  { value: "camel3.13", label: "camel3.13", children: "camel3.13" },
  { value: "camel3.14", label: "camel3.14", children: "camel3.14" },
  { value: "camel3.15", label: "camel3.15", children: "camel3.15" },
  { value: "camel3.16", label: "camel3.16", children: "camel3.16" },
  { value: "camel3.17", label: "camel3.17", children: "camel3.17" },
  { value: "camel3.18", label: "camel3.18", children: "camel3.18" },
  { value: "camel3.19", label: "camel3.19", children: "camel3.19" },
  { value: "camel3.2", label: "camel3.2", children: "camel3.2" },
  { value: "camel3.20", label: "camel3.20", children: "camel3.20" },
  { value: "camel3.21", label: "camel3.21", children: "camel3.21" },
  { value: "camel3.3", label: "camel3.3", children: "camel3.3" },
  { value: "camel3.4", label: "camel3.4", children: "camel3.4" },
  { value: "camel3.5", label: "camel3.5", children: "camel3.5" },
  { value: "camel3.6", label: "camel3.6", children: "camel3.6" },
  { value: "camel3.7", label: "camel3.7", children: "camel3.7" },
  { value: "camel3.8", label: "camel3.8", children: "camel3.8" },
  { value: "camel3.9", label: "camel3.9", children: "camel3.9" },
  { value: "camel4", label: "camel4", children: "camel4" },
  { value: "camel4.1", label: "camel4.1", children: "camel4.1" },
  {
    value: "cloud-readiness",
    label: "cloud-readiness",
    children: "cloud-readiness",
  },
  { value: "discovery", label: "discovery", children: "discovery" },
  { value: "drools", label: "drools", children: "drools" },
  { value: "drools6", label: "drools6", children: "drools6" },
  { value: "eap", label: "eap", children: "eap" },
  { value: "eap6", label: "eap6", children: "eap6" },
  { value: "eap7", label: "eap7", children: "eap7" },
  { value: "eap7.1", label: "eap7.1", children: "eap7.1" },
  { value: "eap8", label: "eap8", children: "eap8" },
  { value: "eapxp", label: "eapxp", children: "eapxp" },
  { value: "eapxp2", label: "eapxp2", children: "eapxp2" },
  { value: "eapxp3", label: "eapxp3", children: "eapxp3" },
  { value: "eapxp5", label: "eapxp5", children: "eapxp5" },
  { value: "fsw", label: "fsw", children: "fsw" },
  { value: "fsw6", label: "fsw6", children: "fsw6" },
  { value: "fuse", label: "fuse", children: "fuse" },
  { value: "fuse6", label: "fuse6", children: "fuse6" },
  { value: "hibernate", label: "hibernate", children: "hibernate" },
  {
    value: "hibernate-search",
    label: "hibernate-search",
    children: "hibernate-search",
  },
  {
    value: "hibernate-search5",
    label: "hibernate-search5",
    children: "hibernate-search5",
  },
  { value: "hibernate4", label: "hibernate4", children: "hibernate4" },
  { value: "hibernate5", label: "hibernate5", children: "hibernate5" },
  { value: "hibernate5.1", label: "hibernate5.1", children: "hibernate5.1" },
  { value: "hibernate5.3", label: "hibernate5.3", children: "hibernate5.3" },
  { value: "hibernate6", label: "hibernate6", children: "hibernate6" },
  { value: "hibernate6.1", label: "hibernate6.1", children: "hibernate6.1" },
  { value: "hibernate6.2", label: "hibernate6.2", children: "hibernate6.2" },
  { value: "jakarta-ee", label: "jakarta-ee", children: "jakarta-ee" },
  { value: "jakarta-ee8", label: "jakarta-ee8", children: "jakarta-ee8" },
  { value: "jakarta-ee9", label: "jakarta-ee9", children: "jakarta-ee9" },
  { value: "java-ee", label: "java-ee", children: "java-ee" },
  { value: "java-ee6", label: "java-ee6", children: "java-ee6" },
  { value: "java-ee7", label: "java-ee7", children: "java-ee7" },
  { value: "jbpm", label: "jbpm", children: "jbpm" },
  { value: "jbpm6", label: "jbpm6", children: "jbpm6" },
  { value: "jws", label: "jws", children: "jws" },
  { value: "jws6", label: "jws6", children: "jws6" },
  { value: "linux", label: "linux", children: "linux" },
  { value: "openjdk", label: "openjdk", children: "openjdk" },
  { value: "openjdk11", label: "openjdk11", children: "openjdk11" },
  { value: "openjdk17", label: "openjdk17", children: "openjdk17" },
  { value: "openjdk18", label: "openjdk18", children: "openjdk18" },
  { value: "openjdk19", label: "openjdk19", children: "openjdk19" },
  { value: "openjdk20", label: "openjdk20", children: "openjdk20" },
  { value: "openjdk21", label: "openjdk21", children: "openjdk21" },
  { value: "openjdk7", label: "openjdk7", children: "openjdk7" },
  { value: "openliberty", label: "openliberty", children: "openliberty" },
  { value: "quarkus", label: "quarkus", children: "quarkus" },
  { value: "quarkus3", label: "quarkus3", children: "quarkus3" },
  { value: "resteasy", label: "resteasy", children: "resteasy" },
  { value: "resteasy3", label: "resteasy3", children: "resteasy3" },
  { value: "rhr", label: "rhr", children: "rhr" },
];
